micronaut:
  application:
    name: ruvalService
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        connection:
          db-type: postgres
    reactive: true
